# El método de k-means

In [3]:
import numpy as np

In [4]:
data = np.random.random(90).reshape(30,3)
data

array([[0.55664103, 0.92912746, 0.94489161],
       [0.28663192, 0.76827158, 0.89527649],
       [0.48251101, 0.70354294, 0.93034281],
       [0.96331158, 0.63355644, 0.34938442],
       [0.3818623 , 0.43669842, 0.47524953],
       [0.08479025, 0.79459378, 0.30035921],
       [0.64480872, 0.16320079, 0.78989192],
       [0.33500942, 0.72772674, 0.06715305],
       [0.94606263, 0.66704371, 0.28821174],
       [0.15007569, 0.88765829, 0.68742919],
       [0.35413015, 0.08471461, 0.29183552],
       [0.71359036, 0.25692293, 0.26821488],
       [0.66926468, 0.40880197, 0.09112598],
       [0.61998789, 0.97348052, 0.57028305],
       [0.48404753, 0.34828973, 0.41742368],
       [0.9907463 , 0.75227299, 0.39687598],
       [0.49720786, 0.81699037, 0.88753228],
       [0.65518935, 0.38619875, 0.47987613],
       [0.40179334, 0.13417108, 0.90928007],
       [0.61506261, 0.57761523, 0.38436546],
       [0.77015086, 0.64868101, 0.1423351 ],
       [0.94516641, 0.24895437, 0.81833049],
       [0.

In [6]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1], data[c2]])
clust_centers

array([[0.64480872, 0.16320079, 0.78989192],
       [0.9907463 , 0.75227299, 0.39687598]])

In [14]:
from scipy.cluster.vq import vq

In [16]:
clusters = vq(data, clust_centers) # PRIMERO MUESTRA A QUE CLUSTER PERTENECE Y LUEGO LA Distancia a los baricentros de su cluster
clusters

(array([1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
        0, 1, 1, 0, 1, 0, 0, 0]),
 array([0.72114217, 0.71099029, 0.58140918, 0.13077359, 0.49289107,
        0.91206518, 0.        , 0.73437769, 0.14515019, 0.8832316 ,
        0.58199166, 0.53447328, 0.5610756 , 0.46525754, 0.44590881,
        0.        , 0.67731859, 0.38202833, 0.27230999, 0.41448773,
        0.35239851, 0.31365135, 0.24739156, 0.59675486, 0.65400823,
        0.2150988 , 0.35827983, 0.14040574, 0.84897224, 0.35900807]))

In [17]:
labels = clusters[0]
labels

array([1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0])

In [29]:
import plotly.plotly as py
import plotly.graph_objs as go
import plotly.offline as ply

In [30]:
x = []
y = []
z = []
x2 = []
y2 = []
z2 = []

for i in range(0, len(labels)):
    if(labels[i] == 0):
        x.append(data[i,0])
        y.append(data[i,1])
        z.append(data[i,2])
        
    else:
        x2.append(data[i,0])
        y2.append(data[i,1])
        z2.append(data[i,2])

cluster1 = go.Scatter3d(
    x=x,
    y=y,
    z=z,
    mode='markers',
    marker=dict(
        size=12,
        line=dict(
            color='rgba(217, 217, 217, 0.14)',
            width=0.5
        ),
        opacity=0.9
    ),
    name="Cluster 0"
)


cluster2 = go.Scatter3d(
    x=x2,
    y=y2,
    z=z2,
    mode='markers',
    marker=dict(
        color='rgb(127, 127, 127)',
        size=12,
        symbol='circle',
        line=dict(
            color='rgb(204, 204, 204)',
            width=1
        ),
        opacity=0.9
    ),
    name="Cluster 1"
)
data2 = [cluster1, cluster2]
layout = go.Layout(
    margin=dict(
        l=0,
        r=0,
        b=0,
        t=30
    )
)

fig = go.Figure(data=data2, layout=layout)
ply.plot(fig, filename='Clusters')


'file://C:\\Users\\Guany\\Documents\\GitHub\\python-ml-course\\notebookspropios\\Clusters.html'

In [21]:
from scipy.cluster.vq import kmeans

In [27]:
kmeans(data, clust_centers)
#CENTROS DE CADA CLUSTER GENERADO, EL ULTIMO NUMERO ES LA SUMA TOTAL DE LOS RESULTADOS MENOS LA DISTANCIA AL BARICENTRO GLOBAL DEL SISTEMA

(array([[0.58366313, 0.39833976, 0.70827696],
        [0.57474086, 0.74281471, 0.37143063]]), 0.3878527837976206)

In [28]:
kmeans(data, 2)

(array([[0.41053747, 0.85414279, 0.71324085],
        [0.66398037, 0.41157071, 0.47000258]]), 0.35985407774463235)